[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hush = "CkevGEmkCSpN3SgS9ptG42qL42vV4aTS8NrhDx29sxF3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
